AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    kawai-dynamoDB-test

    Sample SAM Template for kawai-dynamoDB-test

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
    Function:
        Timeout: 5
        MemorySize: 128

        Tracing: Active
    Api:
        TracingEnabled: true
Resources:
    GetAllBooksFunction:
        Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
        Properties:
            CodeUri: getAllBooks/
            Handler: getAllBooks
            Runtime: go1.x
            Architectures:
                - x86_64
            Events:
                CatchAll:
                    Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                    Properties:
                        Path: /books
                        Method: GET
            Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
                Variables:
                    PARAM1: VALUE
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: kawai-dynamoDB-books-test

    AddBookFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: addBook/
            Handler: addBook
            Runtime: go1.x
            Architectures:
                - x86_64
            Policies:
                - DynamoDBCrudPolicy:
                      TableName: kawai-dynamoDB-books-test
            Events:
                AddBookApi:
                    Type: Api
                    Properties:
                        Path: /add-book
                        Method: POST

        DynamoDBTable:
            Type: AWS::DynamoDB::Table
            Properties:
                TableName: dynamoDB-books-test
                AttributeDefinitions: # テーブルの属性定義
                    - AttributeName: id
                      AttributeType: S
                KeySchema: # プライマリーキーの設定
                    - AttributeName: id
                      KeyType: HASH
                ProvisionedThroughput:
                    # 1 capasity unit : 1秒間に1KBの読み込みまたは書き込み
                    ReadCapacityUnits: 5
                    WriteCapacityUnits: 5
                StreamSpecification:
                    StreamViewType: NEW_IMAGE

    ApplicationResourceGroup:
        Type: AWS::ResourceGroups::Group
        Properties:
            Name:
                Fn::Sub: ApplicationInsights-SAM-${AWS::StackName}
            ResourceQuery:
                Type: CLOUDFORMATION_STACK_1_0
    ApplicationInsightsMonitoring:
        Type: AWS::ApplicationInsights::Application
        Properties:
            ResourceGroupName:
                Ref: ApplicationResourceGroup
            AutoConfigurationEnabled: "true"
    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
